---
- name: Create directory
  ansible.builtin.file:
    state: directory
    path: "/etc/sympa/mail_tt2"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: '0775'

- name: Custom email templates
  ansible.builtin.copy:
    src: "{{ item  }}"
    dest: "/etc/sympa/mail_tt2/{{ item | basename }}"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: '0644'
  loop: "{{ sympa_email_templates }}"

