---
- name: Ensures git is installed.
  ansible.builtin.package:
    name: git
    state: present

- name: Download sources from repository
  ansible.builtin.git:
    repo: "{{ sympa_repository_url }}"
    dest: "{{ sympa_source_directory }}"
    force: true
    version: "{{ sympa_repository_version }}"
  become_user: "{{ sympa_unix_user }}"
  vars:
    ansible_ssh_pipelining: true

- name: Import tasks to install Perl modules
  ansible.builtin.import_tasks: perl-modules.yml
    
