---
- name: Create directory
  ansible.builtin.file:
    state: directory
    path: "/etc/sympa/scenari"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: '0775'

- name: Custom scenari
  ansible.builtin.copy:
    src: "{{ item  }}"
    dest: "/etc/sympa/scenari/{{ item | basename }}"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: '0644'
  loop: "{{ sympa_scenari }}"
  tags:
    - sympa-scenari
