---

- name: Install logging tools
  ansible.builtin.package:
    name:
      - rsyslog
      - logrotate

- name: Ensure that rsyslog is enabled and running
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true

- name: Create sympa log file
  ansible.builtin.file:
    dest: /var/log/sympa.log
    state: touch
    mode: 0640
    owner: "{{ sympa_rsyslog_unix_user }}"
    group: "{{ sympa_unix_group }}"
    access_time: preserve
    modification_time: preserve
  tags: syslog
  
- name: Install custom rsyslog conf file
  ansible.builtin.template:
    src: syslog.conf.j2
    dest: /etc/rsyslog.d/sympa.conf
    owner: root
    group: root
    mode: 0644
  tags: syslog
  notify: restart rsyslog

- name: Configure logrotate
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/sympa
    owner: root
    group: root
    mode: 0644
  tags: logrotate
  
